add_dropout: true
batch_size: 64
data_dir: /home/tnguyen/Documents/Emotion_recognition/Multimodal_Emotion_Recognition_for_Geriatric_Medecine/data/EmoData
device: cuda
duration: 3
epochs: 150
full_audio_length: false
hop_length: 512
learning_rate: 0.00001
model_name: wav2vec2
n_fft: 2048
n_frames: null
n_mels: 16
target_sr: 16000
transform: spectrogram
verbose: false
training: finetuned
optimizer: adam
augmentation: false
RCS: 0
database: french_2
wav2vec2_path: facebook/wav2vec2-base-960h