add_dropout: true
batch_size: 64
data_dir: /home/tnguyen/Documents/Emotion_recognition/Multimodal_Emotion_Recognition_for_Geriatric_Medecine/data/EmoData
device: cuda
duration: 3
epochs: 150
filters:
- 32
- 64
- 128
full_audio_length: false
hop_length: 512
learning_rate: 0.001
model_name: resnet18
n_fft: 2048
n_frames: null
n_mels: 16
target_sr: 22050
transform: spectrogram
verbose: false
training: finetuned
optimizer: adam
augmentation: false
RCS: 0
database: enterface